# This workflow will lint the project using flake8. Tests could be added later but would require gamera.
# This workflow only applies to the 
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Biollante Rodan Job
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 2.7
      uses: actions/setup-python@v2
      with:
        python-version: 2.7
    - name: Install flake8
      run: |
        python -m pip install --upgrade pip
        pip install flake8
        # if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Lint with flake8
      run: |
        flake8 ./job/ --count --statistics
