# This workflow will lint the project using flake8. Tests could be added later but would require gamera.
# This workflow only applies to the 
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Biollante Rodan Job
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 2.7
      uses: actions/setup-python@v2
      with:
        python-version: 2.7
    - name: Install flake8
      run: |
        python -m pip install --upgrade pip
        pip install flake8
        # if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 ./job/ --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 ./job/ --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
